---
title: "Final Project Yates"
output: html_document
---

```{r setup, include=FALSE, message = FALSE, error = FALSE}
rm(list = ls())
setwd("/Users/georgeyates/Desktop/Econ 43")

# Load packages
library(doBy)
library(dplyr)
library(foreign)
library(gdata)
library(readstata13)
library(sandwich)
library(stargazer)
library(ISwR)

library(psych)
library(car)
library(fpp2)
library(TTR)
library(gridExtra)
library(maps)
library(rgeos)
library(maptools)
library(ggplot2)
library(rgdal)
library(leaflet)
library(tibble)
library(mapproj)
library(ggmap)
library(htmltab)
library(openintro)
library(rgl)



options(scipen = 9)

# function for corrected standard error for heteroskedacticity
cse <- function(reg) {
  rob = sqrt(diag(vcovHC(reg, type = "HC1")))
  return(rob)
}

```



```{r cars, echo=FALSE , message = FALSE, error = FALSE }
#================================================
# Load Data sets
#================================================

# Read county election data
electionData <- read.csv("2016_US_County_Level_Presidential_Results.csv")
url <- "https://www.infoplease.com/state-abbreviations-and-state-postal-codes"
abbreviations <- htmltab(doc=url, which=1)
abbreviations$`State/District` <- sapply(abbreviations$`State/District`, tolower)
electionData <- merge(electionData, abbreviations, by.x="state_abbr", by.y="Postal Code")


# create better vote differential variable
electionData$vote_differential = ifelse(electionData$per_dem > electionData$per_gop,
                                        electionData$per_dem - electionData$per_gop,
                                        electionData$per_gop - electionData$per_dem)

# Read Chetty Opportunity data
chetty <- read.dta("Chetty_opportunity.dta")

# Merge Data 
merge_1 <- merge(electionData, chetty, by.x="combined_fips", by.y="county_id")

# Get map data for US
states <- map_data("state")

# read and subset county map data
counties <- map_data("county")
ca_counties <- subset(counties, region=="california")

# Read additional CA data
ca_demographics <- read.csv("dof_dru_pop_1970_2050_csya_wide.csv")
ca_demographics <- subset(ca_demographics, ca_demographics$year==2016)
ca_demographics$county = sapply(ca_demographics$county, tolower)

# Read poverty data, election data
povertydata <- read.csv("PovertyLevels.csv")
electiondata2 <- read.csv("ElectionResult.csv")

# Read election affil data
electionaffil = read.csv("ElectionAffil.csv")

# Racial Data
racedata = read.csv("RacialStats.csv")

# read county complete data
data(countyComplete)

# Social Capital, Health, Religion Data
SocialCapital <- read.csv("social_capital.csv", header=TRUE, sep=",")
Health <- read.csv("county_health.csv", header=TRUE, sep=",")
Religion <- read.csv("county_religion.csv", header=TRUE, sep=",")
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE, message = FALSE, error = FALSE}
#================================================
# Story #1: The 2016 General Election at a Glance
#================================================

# Aggregate percentage vote data variable, vote differential by state
statePercents <- aggregate(electionData[c("per_dem","per_gop")], by=list(electionData$`State/District`), mean)
stateDifferentials <- aggregate(electionData[c("vote_differential")], by=list(electionData$`State/District`), mean)

# Summary tables of Percentage Votes, Differentials
stargazer(statePercents, type="text", median=TRUE, digits=2)
stargazer(stateDifferentials, type="text", median=TRUE, digits =2)

# Choropleth map of vote differentials
diff_map <- merge(states, stateDifferentials, by.x="region", by.y="Group.1", all.y=TRUE)
diff_map <- arrange(diff_map, group, order)
ggplot(diff_map, aes(x=long, y=lat, group=group, fill=vote_differential)) +
  geom_polygon(colour="black") +
  coord_map("polyconic")

# Choropleth map of pct gop
gop_map <- merge(states, statePercents, by.x="region", by.y="Group.1", all.y=TRUE)
gop_map <- arrange(gop_map, group, order)
ggplot(gop_map, aes(x=long, y=lat, group=group, fill=per_gop)) +
  geom_polygon(colour="black") +
  scale_fill_continuous(low='thistle2', high='darkred', guide='colorbar') +
  coord_map("polyconic") 


#================================================
# Story #2: The 2016 Election in California
#================================================

# Subset election, merged election/Chetty data for California
ca_elections <- subset(electionData, state_abbr=="CA")
ca_merge <- subset(merge_1, state_abbr=="CA")


# Make an aggregate statistics data set
ca_aggr <- aggregate(ca_elections[c("per_dem","per_gop", "vote_differential")], 
                     by=list(ca_elections$county_name), mean)
stargazer(ca_aggr, type="text", median=TRUE, digits=2)

# Various plots relating to vote percentages and differentials
ggplot(ca_aggr, aes(x=per_dem)) + geom_line(stat="density", color="blue", size=1.5)
ggplot(ca_aggr, aes(x=per_gop)) + geom_line(stat="density", color="red", size=1.5)
ggplot(ca_aggr, aes(x=per_dem, y=vote_differential)) + geom_point(size=2.5)

# Make a choropleth map of percentage DEM by county 
ca_merge$county_name.y = sapply(ca_merge$county_name.y, tolower)
ca_data_map <- merge(ca_counties, ca_merge, by.x="subregion", by.y="county_name.y")
ca_data_map <- arrange(ca_data_map, order)
ggplot(ca_data_map, aes(x=long, y=lat, group=group, fill=per_dem)) + geom_polygon(colour="black") +
  coord_map("polyconic")

#================================================
# Story #3: Socioeconomic Status and Voting in CA
#================================================

# Scatterplots with socioeconomic data and voting outcomes, regression lines included
ggplot(ca_merge, aes(x=frac_middleclass, y=per_dem)) + geom_point(size=2.5) + geom_smooth(method="lm")
ggplot(ca_merge, aes(x=frac_middleclass, y=per_gop)) + geom_point(size=2.5) + geom_smooth(method="lm")
ggplot(ca_merge, aes(x=gini, y=per_gop)) + geom_point(size=2.5) + geom_smooth(method="lm")

# Choropleth map of GINI by county, frac_middle class by county
ggplot(ca_data_map, aes(x=long, y=lat, group=group, fill=gini)) +
  geom_polygon(color="black") +
  coord_map("polyconic")
ggplot(ca_data_map, aes(x=long, y=lat, group=group, fill=frac_middleclass)) + 
  geom_polygon(color="black") +
  coord_map("polyconic")

# Gender ratios and election outcome
ca_demographics$pct_male = (ca_demographics$pop_male/ca_demographics$pop_total)
ca_demographics$pct_fem = (ca_demographics$pop_female/ca_demographics$pop_total)
ca_dem_agr <- aggregate(ca_demographics[c("pct_male","pct_fem")], by=list(ca_demographics$county),
                        mean)
ca_genders <- merge(ca_merge, ca_dem_agr, by.x="county_name.y", by.y="Group.1")

# scatterplots of per_dem/per_gop on gender ratio
ggplot(ca_genders, aes(x=pct_male, y=per_dem)) + geom_point(size=2.5) 
ggplot(ca_genders, aes(x=pct_fem, y=per_dem)) + geom_point(size=2.5) + geom_smooth() 
ggplot(ca_genders, aes(x=pct_male, y=per_gop)) + geom_point(size=2.5) + geom_smooth()
ggplot(ca_genders, aes(x=pct_fem, y=per_gop)) + geom_point(size=2.5) 

#================================================
# Story #4: Poverty Levels and Voter Turnout
#================================================

mergedd <- merge(x=povertydata, y=electiondata2, by.x="X.1", by.y="State")



ggplot(mergedd, aes(x=X.2.x, y=Turnout.Rates)) + geom_point() +
  geom_text(aes(label=X.1)) + xlab("Percentage of Population below Poverty Line") + ylab("Voter Turnout Rate")

#================================================
# Story #5: Poverty and Votes for Trump
#================================================

mergedaf <- merge(x=povertydata, y=electionaffil, by.x="X.1", by.y="X")

ggplot(mergedaf, aes(x=X.2.x, y=Donald)) + geom_point() +
  geom_text(aes(label=X.1)) + xlab("Percentage of Population Below Poverty Line") + ylab("Percentage of Voters for Donald Trump")


#================================================
# Story #6: Racial Status and Voting
#================================================

racedata$State.Territory <- sapply(racedata$State.Territory, tolower)
race_map <- merge(states, racedata, by.x="region", by.y="State.Territory", all.y=TRUE)
is.factor(race_map$Pop.1990)

race_map$Pop.1990 <- as.numeric(race_map$Pop.1990)
race_map$Pop.2000 <- as.numeric(race_map$Pop.2000)
race_map$Pop.2012 <- as.numeric(race_map$Pop.2012)

m1 <- ggplot(race_map, aes(x=long, y=lat, group=group, fill=Pop.1990)) +
  geom_polygon(colour="black") +
  coord_map("polyconic") +
  ggtitle("Percentage of White People By State 1990")

m2 <- ggplot(race_map, aes(x=long, y=lat, group=group, fill=Pop.2000)) +
  geom_polygon(colour="black") +
  coord_map("polyconic") +
  ggtitle("Percentage of White People By State 2000")

m3 <- ggplot(race_map, aes(x=long, y=lat, group=group, fill=Pop.2012)) +
  geom_polygon(colour="black") +
  coord_map("polyconic") +
  ggtitle("Percentage of White People By State 2012")

grid.arrange(m1,m2, m3)

#================================================
# Story #7: Adult Smokers and GOP Votes
#================================================

# Merges
County1 <- merge(Health,Religion, by.x="county_fips",by.y="county_fips",all.x= TRUE, all.y = TRUE)
County2 <- merge(County1,SocialCapital, by.x="county_fips", by.y="fips",all.x= TRUE, all.y= TRUE)
County3 <- merge (County2, chetty, by.x="county_fips", by.y="county_id",all.x= TRUE,all.y=TRUE)
County4 <- merge (County3, electionData, by.x="county_fips", by.y="combined_fips",all.x= TRUE, all.y=TRUE)
Master <-  merge(County4, countyComplete, by.x="county_fips", by.y="FIPS",all.x+TRUE, all.y=TRUE)

# Plot of per_gop on adult smokers
ggplot(data=Master, aes(x=p_adult_smokers, y=per_gop)) +
  geom_point(shape=0) + geom_smooth(method="lm") +
  labs(title="Percent Adult Smokers vs. GOP") + 
  labs(x="% Adult Smokers", y="% of people who voted GOP")


#================================================
# Story #8: Social, Economic Factors and pct GOP
#================================================

ggplot(data=Master, aes(x=p_singleparent_households, y=unemp_rate)) +
  geom_point(shape=0)+ geom_smooth(method="lm") +
  labs(title="% Single Parent Households and Unemployment Rate") + 
  labs(x="% Single-Parent Households", y="Unemployment Rate")

# % People in Poor or Fair Health & Unemployment Rate
ggplot(data=Master, aes(x=p_poor_fair_health, y=unemp_rate)) +
  geom_point(shape=0) + geom_smooth(method="lm") + 
  labs(title="% People in Poor or Fair Health and Unemployment Rate") + 
  labs(x="% People in Poor or Fair Health", y="Unemployment Rate")

# % of People Who Voted GOP & % of Unemployment Rate
ggplot(data=Master, aes(x=unemp_rate, y=per_gop)) +
  geom_point(shape=0)+ geom_smooth(method="lm") +
  labs(title="Unemployment Rate vs. GOP") + 
  labs(x="% Unemployment Rate", y=" % Percent GOP")

#================================================
# Story #9: Various election regressions
#================================================

reg1 <- lm(per_gop ~ p_af_am + p_singleparent_households + p_phys_inactive, data=Master)

reg2 <- lm(per_gop ~ p_singleparent_households + p_phys_inactive + violent_crime_rate,  data=Master)

reg3 <- lm(per_gop ~ p_poor_fair_health + violent_crime_rate + p_adult_smokers,  data=Master)

stargazer(reg1, reg2, reg3, 
          se=list(cse(reg1),cse(reg2),cse(reg3)), 
          title="Regression Results", type="text", 
          df=FALSE, digits=3)

#================================================
# Story #10: Forecasting Southern Australian Electricity Sales
#================================================

autoplot(elecsales)
trend <- seq_along(elecsales)
(fit1 <- auto.arima(elecsales, d=0, xreg=trend))
(fit2 <- auto.arima(elecsales, d=1))

fc1 <- forecast(fit1, xreg = cbind(trend = length(elecsales) + 1:10))
fc2 <- forecast(fit2, h=10)
autoplot(elecsales) +
  autolayer(fc1, series="Deterministic trend forecast") +
  ggtitle("Annual electricity sales: South Australia") +
  xlab("Year") + ylab("GWH") +
  guides(colour=guide_legend(title="Forecast"))
autoplot(elecsales) +
  autolayer(fc2, series="Stochastic trend forecast") +
  ggtitle("Annual electricity sales: South Australia") +
  xlab("Year") + ylab("GWH") +
  guides(colour=guide_legend(title="Forecast"))

#================================================
# Story #11: Forecasting Google Stock Price
#================================================

autoplot(goog200)
trend2 <- seq_along(goog200)
(fit3 <- auto.arima(goog200, d=0, xreg=trend2))
(fit4 <- Arima(goog200, order=c(0,1,1),include.drift=TRUE))

fc3 <- forecast(fit3, xreg = cbind(trend = length(goog200) + 1:10))
fc4 <- forecast(fit4, h=10)
autoplot(goog200) +
  autolayer(fc3, series="Deterministic trend forecast") +
  ggtitle("Google Stock Price") +
  xlab("Days") + ylab("Dollars($)") +
  guides(colour=guide_legend(title="Forecast"))
autoplot(goog200) +
  autolayer(fc4, series="Stochastic trend forecast") +
  ggtitle("Google Stock Price") +
  xlab("Days") + ylab("Dollars($)") +
  guides(colour=guide_legend(title="Forecast"))

#================================================
# Story #12: Forecasting Saudi Oil Production
#================================================

autoplot(oil)
trend3 <- seq_along(oil)
(fit5 <- auto.arima(oil, d=0, xreg=trend3))
(fit6 <- Arima(oil, order=c(0,1,1),include.drift=TRUE))

fc5 <- forecast(fit5, xreg = cbind(trend = length(oil) + 1:10))
fc6 <- forecast(fit6, h=10)
autoplot(oil) +
  autolayer(fc5, series="Deterministic trend forecast") +
  ggtitle("Saudi Arabian Oil Production") +
  xlab("Year") + ylab("Millions of Tons") +
  guides(colour=guide_legend(title="Forecast"))
autoplot(oil) +
  autolayer(fc6, series="Stochastic trend forecast") +
  ggtitle("Saudi Arabian Oil Production") +
  xlab("Year") + ylab("Millions of Tons") +
  guides(colour=guide_legend(title="Forecast"))


options(warn=-1)
options(warn=0)        

```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
